# The official Python image from the Docker Hub
FROM python:3.13-slim

# Set the working directory in the container
WORKDIR /script

# Copy the current directory contents into the container at /app
COPY . .

# Run main.py when the container launches
CMD ["python", "main.py"]